mkList/appProduct/urls.py
from django.urls import path
from . import views

app_name = 'appProduct'             # Con este nombre es invocado en URL del core proyecto
urlpatterns =[
     #path('<slug:category_slug>/<product_slug>/', views.product,  name='product'),
     path('add_categoria/',        views.add_categoria,      name='add_categoria'),
     path('list_categoria/',       views.list_categoria,     name='list_categoria'),
     path('mod_categoria/<id>/',   views.mod_categoria,      name='mod_categoria'),
     path('del_categoria/<id>/',   views.del_categoria,      name='del_categoria'),
     path('add_colores/', views.add_colores,      name='add_colores'),
     path('list_colores/', views.list_colores,    name='list_colores'),
     path('mod_colores/<id>/', views.mod_colores, name='mod_colores'),
     path('del_colores/<id>/', views.del_colores, name='del_colores'),
     path('add_bulbo/', views.add_bulbo,      name='add_bulbo'),
     path('list_bulbo/', views.list_bulbo,    name='list_bulbo'),
     path('mod_bulbo/<id>/', views.mod_bulbo, name='mod_bulbo'),
     path('del_bulbo/<id>/', views.del_bulbo, name='del_bulbo'),
     path('<slug:category_slug>/', views.category,           name='category'),
]  

mkList/client/urls.py
from django.urls import path
from . import views

app_name = 'client'                    # Con este nombre es invocado en URL del core proyecto
urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name='logout'),
    path('customer/<str:pk_test>/', views.customer, name='customer'),  # Viene el ID del customer

    path('gallery/', views.gallery, name='gallery'),

    ]

mkList/mkList/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls')),               # Importa incluye las url de la app
    path('', include('appClient.urls')),
    path('', include('appProduct.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mkList/appProduct/models.py
from django.db import models
from django.db.models.fields import CharField

from io import BytesIO
from PIL import Image
from django.core.files import File

#--------------------------------------------------------------------------------------------
class Categoria(models.Model):
        categoria=models.CharField(max_length=25, unique=True)
        slug = models.SlugField(max_length=255)
        orden = models.IntegerField(default=0)

        def __str__(self):
            return self.categoria

        class Meta():
            ordering = ['categoria']

#--------------------------------------------------------------------------------------------
class Color(models.Model):
        color=models.CharField(max_length=20, unique=True)

        def __str__(self):
            return self.color

        class Meta():
            ordering = ['color']
#----------------------------------------------------------------------------------
#https://www.youtube.com/watch?v=Rr1-UTFCuH4

def upload_to(instance, filename):
    return 'uploads/%s/%s' % (instance.categoria, filename)

class Bulbo(models.Model):
    codigo=CharField(max_length=10, unique=True)
    categoria=models.ForeignKey(Categoria, related_name='bulbos', on_delete=models.CASCADE)
    variedad=CharField(max_length=12)
    color=models.ForeignKey('color', on_delete=models.DO_NOTHING)
    size=CharField(max_length=10)
    creado_en=models.DateField(auto_now_add=True)
    modificado_en=models.DateField(auto_now=True)
    image = models.ImageField(upload_to=upload_to,blank=True, null=True)
    thumbnail = models.ImageField(upload_to=upload_to,blank=True, null=True)
    
    @property
    def bulbo(self):
        return "%s %s %s %s"%(self.categoria, self.variedad, self.color, self.size)

    class Meta():
        ordering = ['categoria', 'variedad', 'color', 'size']
        constraints = [models.UniqueConstraint(fields=['categoria', 'variedad', 'color', 'size'], name='articulo')]
        indexes = [
            models.Index(fields=['codigo']),
            models.Index(fields=['categoria', 'variedad', 'color', 'size'], name='bulbo'),]

    def __str__(self): 
        return self.bulbo

    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail=self.make_thumbnail(self.image)
                self.save()
                return self.thumbnail.url
            else:
                return ('/amedia/uploads/placeholder.jpg')

    def make_thumbnail(self, image, size=(200, 200)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io = BytesIO()
        img.save(thumb_io, 'JPEG', quality=85)
        thumbnail = File(thumb_io, name=image.name)

        return thumbnail

mkList/appProduct/forms.py
from django import forms
from django.forms.widgets import TextInput


from .models import Categoria, Color, Bulbo

#--------------------------------------------------------------------------------------------
class CategoriaForm(forms.ModelForm):
    class Meta:
        model= Categoria
        fields= '__all__'

        widgets = {
            'categoria' : TextInput(attrs={"class":"form-control mb-3", 
                                        "placeholder":"Ingresar",
                                        "autocomplete":"off"}),

            'slug' : TextInput(attrs={"class":"form-control mb-3", 
                                        "placeholder":"Ingresar slug",
                                        "autocomplete":"off"}),

            'orden' : forms.NumberInput(attrs={"class":"form-control mb-3",}),
           
        }

#--------------------------------------------------------------------------------------------
class ColorForm(forms.ModelForm):
    class Meta:
        model= Color
        fields= '__all__'

        widgets = {
            'color' : TextInput(attrs={"class":"form-control mb-3", 
                                        "placeholder":"Ingresar",
                                        "autocomplete":"off"}),
           
        }

#----------------------------------------------------------------------------------------------
class BulboForm(forms.ModelForm):
    class Meta:
        model= Bulbo
        fields= '__all__'

        widgets = {

            'image': forms.ClearableFileInput(attrs={'class': 'form-control form-control-sm mb-3',
                                                        }),
            'thumbnail': forms.ClearableFileInput(attrs={'class': 'form-control form-control-sm mb-3',
                                                        }),
            
        }

    def __init__(self, *args, **kwargs):
        super(BulboForm, self).__init__(*args, **kwargs)
        #self.fields['usuario'].widget = forms.HiddenInput()
        #self.fields["codigo"].disabled = True

mkList/appProduct/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Categoria, Color
from .forms import *
from django.contrib import messages     # Me permite enviar messages 


#--------------------------------------------------------------------------------------------------------------------
def category(request, category_slug):
    print (category_slug)
    categoria = get_object_or_404(Categoria, slug=category_slug)
    return render(request,  'client/gallery_category.html', {'categoria': categoria})

def add_categoria(request):
    data = {'form':CategoriaForm}

    if request.method == 'POST':
        form = CategoriaForm(data=request.POST,)
        if form.is_valid():
            form.save()
            messages.success(request, 'Categoria ingresada correctamente')
        else:
            data["form"] = form

    return render(request, 'appProduct/categorias/add.html', data)
    
def list_categoria(request):
    categorias=Categoria.objects.all()
    data = {'categorias' : categorias}
    return render(request, 'appProduct/categorias/list.html', data)

def mod_categoria(request, id):
    icategoria=get_object_or_404(Categoria, id=id)
    data = {'form' : CategoriaForm(instance=icategoria)}
    if request.method == 'POST':
        form = CategoriaForm(data=request.POST, instance=icategoria, )
        if form.is_valid():
            form.save() 
            messages.success(request, 'Categoria modificada correctamente')
            return redirect(to='appProduct:list_categoria')
        data["form"] = form

    return render(request, 'appProduct/categorias/mod.html', data)

def del_categoria(request, id):
    icategoria=get_object_or_404(Categoria, id=id)
    icategoria.delete()
    messages.success(request, 'Categoria eliminada')

    return redirect(to='appProduct:list_categoria')

#--------------------------------------------------------------------------------------------------------------------

def add_colores(request):
    data = {'form':ColorForm}

    if request.method == 'POST':
        form = ColorForm(data=request.POST,)
        if form.is_valid():
            form.save()
            messages.success(request, 'Color ingresado correctamente')
        else:
            data["form"] = form

    return render(request, 'appProduct/colores/add.html', data)
    
def list_colores(request):
    colores=Color.objects.all()
    data = {'colores' : colores}
    return render(request, 'appProduct/colores/list.html', data)

def mod_colores(request, id):
    icolor=get_object_or_404(Color, id=id)
    data = {'form' : ColorForm(instance=icolor)}
    if request.method == 'POST':
        form = ColorForm(data=request.POST, instance=icolor, )
        if form.is_valid():
            form.save() 
            messages.success(request, 'Color modificado correctamente')
            return redirect(to='appProduct:list_colores')
        data["form"] = form

    return render(request, 'appProduct/colores/mod.html', data)

def del_colores(request, id):
    icolor=get_object_or_404(Color, id=id)
    icolor.delete()
    messages.success(request, 'Color eliminado')

    return redirect(to='appProduct:list_colores')


#-----------------------------------------------------------------

def add_bulbo(request):
    if request.method == 'POST':
        form = BulboForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Bulbo ingresado correctamente')
            return redirect(to='appProduct:list_bulbo')
    else:
        form = BulboForm()

    return render(request, 'appProduct/mnt_bulbo/add_bulbo.html', {'form': form})




def list_bulbo(request):
    bulbos=Bulbo.objects.all()
    data = {'bulbos' : bulbos}
    return render(request, 'appProduct/mnt_bulbo/list_bulbo.html', data)

def mod_bulbo(request, id):
    ibulbo=get_object_or_404(Bulbo, id=id)
    data = {'form' : BulboForm(instance=ibulbo)}
    if request.method == 'POST':
        form = BulboForm(request.POST, request.FILES, instance=ibulbo, )
        if form.is_valid():
            form.save() 
            messages.success(request, 'Bulbo modificado correctamente')
            return redirect(to='appProduct:list_bulbo')
        
        data["form"] = form

    return render(request, 'appProduct/mnt_bulbo/mod_bulbo.html', data)

def del_bulbo(request, id):
    ibulbo=get_object_or_404(Bulbo, id=id)
    ibulbo.delete()
    messages.success(request, 'Bulbo eliminado')

    return redirect(to='appProduct:list_bulbo')

mkList/templates/appProduct/categorias/add.html
{% extends '../../base.html' %}    <!-- 1 Heredar desde base -->
{% block content %}              <!-- 2 Block contenido -->
{% load crispy_forms_tags %}

<div class="container text-secondary fw-md-bolder mt-md-5 mb-md-5 mt-sm-1 mb-sm-1">
    
<div class="row p-sm-0 p-md-5">
    <div class="col-6 offset-sm-3">
        <div class="d-flex justify-content-center card border border-primary bg-secondary">
            <div class="card-body d-flex flex-column justify-content-center m-1 pt-3 border border-primary bg-light">
                <h3 class="text-dark mt-1 text-center">Ingreso de categorias</h3>
                <form action="" class="d-flex flex-column justify-content-around mt-1" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row"><div class="col-8">{{ form.categoria | as_crispy_field }}</div></div>
                    
                    <div class="row"><div class="col-8"> {{ form.slug | as_crispy_field }}</div>
                                     <div class="col-4">{{ form.orden | as_crispy_field }}</div>
                    </div>
                   
                    
                    

                    <div class="d-flex border-top border-2 border-secondary p-1 justify-content-md-end mt-5">
                         <input type="reset" value="Limpiar" class="btn btn-secondary mb-0 ">
                         &nbsp; &nbsp; &nbsp;
                         <button type="submit" id="btnEnviar" class="btn btn-primary mb-0">Guardar</button>
                    </div>

                    <div class="text-muted text-center fw-bold">
                        {{mensaje}}
                    </div>

                </form>
                
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}                      <!-- 2 Block contenido -->

mkList/templates/appProduct/categorias/list.html
{% extends '../../base.html' %}

{% block js %}

<script>
  function delCategoria(id) {

    Swal.fire({
      title: 'Esta seguro ?',
      text: 'Esta accion es irreversible!',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonText: 'Si, eliminalo!',
      confirmButtonColor: '#dc3545',
      cancelButtonText: 'No, no eliminar.'
    }).then((result) => {
      if (result.value) {
        window.location.href = "/del_categoria/" + id + "/"

      }
    })

  }
</script>

{% endblock %}
{% load static %}

{% block content %}

<div class="card mt-1 border-0">
  <div class="card-body">
    <div class="container text-left text-black-50 mt-1 mb-1 border-bottom">
      
      <div class="row">
        <div class="col">
          <h2>
            <blockquote>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Listado de categorias</blockquote>
          </h2>
        </div>

        <div class="col">
          <a href="{% url 'appProduct:add_categoria' %}">
            <img title="Crear"
             src="{% static '/images/iconos/edit.jpg' %}" alt="Crear" height="45" width="" /></a>
        </div>

      </div>
    </div>
    <div class="container table-responsive">

      <table class="table table-striped table-borderless table-hover">
        <caption>Fin de categorias</caption>
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Slug</th>
            <th scope="col">Orden</th>
          </tr>
        </thead>
        <tbody>
          {% for categoria in categorias %}
          <tr>
            <td>{{ categoria.id }}</td>
            <td>{{ categoria.categoria | title }}</td>
            <td>{{ categoria.slug }}</td>
            <td>{{ categoria.orden }}</td>
            <td>
              <div>
                <a href="{% url 'appProduct:mod_categoria' categoria.id %}">
                  <img title="Modificar" src="{% static 'images/iconos/pyedit24.png' %}" alt="Modificar" /></a>
                &nbsp; &nbsp; &nbsp;
                <a href="#" onclick="delCategoria({{ categoria.id }})">
                  <img title="Eliminar" src="{% static 'images/iconos/pydelete24.png' %}" alt="Eliminar" /></a>
                  
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <hr>
      <div>

      </div>
    </div>
  </div>
</div>


{% endblock %}

mkList/templates/appProduct/categorias/mod.html
{% extends '../../base.html' %}    <!-- 1 Heredar desde base -->
{% block content %}              <!-- 2 Block contenido -->
{% load crispy_forms_tags %}

<div class="container text-secondary fw-md-bolder mt-md-5 mb-md-5 mt-sm-1 mb-sm-1">   
<div class="row p-sm-0 p-md-5">
    <div class="col-6 offset-sm-3">
        <div class="d-flex justify-content-center card border border-primary bg-secondary">
            <div class="card-body d-flex flex-column justify-content-center m-1 pt-3 border border-primary bg-light">
                <h3 class="text-dark mt-1 text-center">Modificacion de categorias</h3>
                <form action="" class="d-flex flex-column justify-content-around mt-1" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row"><div class="col-8">{{ form.categoria | as_crispy_field }}</div></div>
                    <div class="row"><div class="col-8"> {{ form.slug | as_crispy_field }}</div>
                                     <div class="col-4">{{ form.orden | as_crispy_field }}</div>
                    </div>
                   
                    <div class="d-flex border-top border-2 border-secondary p-1 justify-content-md-end mt-5">
                         <input type="reset" value="Limpiar" class="btn btn-secondary mb-0 ">
                         &nbsp; &nbsp; &nbsp;
                         <button type="submit" id="btnEnviar" class="btn btn-primary mb-0">Guardar cambios</button>
                    </div>
                    <div class="text-muted text-center fw-bold">
                        {{mensaje}}
                    </div>

                </form>
                
            </div>
        </div>
    </div>
</div>
</div>



{% endblock %}                      <!-- 2 Block contenido -->