mkList/appClient/urls.py
from django.urls import path

from . import views

app_name = 'appClient'                                      # Con este nombre es invocado en URL del core proyecto
urlpatterns = [

    path('cliente/', views.cliente, name='cliente'),                   # List
    path('nada/', views.nada, name='nada'),
    path('mod_cliente/<id>/', views.mod_cliente, name='mod_cliente'),  # modifica desde lista pasa id user al cliente
    path('crea_cliente/', views.crea_cliente, name='crea_cliente'),    # Crea desde lista
    path('mod_datos/<user>/', views.mod_datos, name='mod_datos'),      # crea modifica desde login pasa el user al cliente
    ]

mkList/appProduct/urls.py
from django.urls import path
from . import views

app_name = 'appProduct'             # Con este nombre es invocado en URL del core proyecto
urlpatterns =[
     #path('<slug:category_slug>/<product_slug>/', views.product,  name='product'),
     path('add_categoria/',        views.add_categoria,      name='add_categoria'),
     path('list_categoria/',       views.list_categoria,     name='list_categoria'),
     path('mod_categoria/<id>/',   views.mod_categoria,      name='mod_categoria'),
     path('del_categoria/<id>/',   views.del_categoria,      name='del_categoria'),
     path('add_colores/', views.add_colores,      name='add_colores'),
     path('list_colores/', views.list_colores,    name='list_colores'),
     path('mod_colores/<id>/', views.mod_colores, name='mod_colores'),
     path('del_colores/<id>/', views.del_colores, name='del_colores'),
     path('add_bulbo/', views.add_bulbo,      name='add_bulbo'),
     path('list_bulbo/', views.list_bulbo,    name='list_bulbo'),
     path('mod_bulbo/<id>/', views.mod_bulbo, name='mod_bulbo'),
     path('del_bulbo/<id>/', views.del_bulbo, name='del_bulbo'),
     path('<slug:category_slug>/', views.category,           name='category'),
]  

mkList/client/urls.py
from django.urls import path
from . import views

app_name = 'client'                    # Con este nombre es invocado en URL del core proyecto
urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name='logout'),
    path('customer/<str:pk_test>/', views.customer, name='customer'),  # Viene el ID del customer

    path('gallery/', views.gallery, name='gallery'),

    ]

mkList/mkList/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls')),               # Importa incluye las url de la app
    path('', include('appClient.urls')),
    path('', include('appProduct.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mkList/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title> {% block title %}
            {% endblock %}  Show Code</title>

            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Roboto:wght@100;400&display=swap" rel="stylesheet">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" 
        crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
                                    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" 
        crossorigin="anonymous"></script>
</head>

<body>

   
            {% include 'navbar.html' %}
            
            <section class="section"></section>
            <div class="container-fluid">
            {% block content %}

            {% endblock %}

          </div>
    </section>   
    <div class="container-fluid border border-secondary border-1 mt-3" style="background:hwb(108 43% 14%);">
        <footer class="text-center">
            <h3 class="p-3 me_footer">Codigo - Temporada 2022</h3>
            
        </footer>

        <script src="{% static 'js/sweetalert2.all.min.js' %}"></script>
        
        {% if messages %}

            {% for m in messages %}
                <script>
                    Swal.fire({
                        "title": "Accion exitosa",
                        "text" : "{{m}}",
                        "icon" : "success"
                    })
                </script>
                
            {% endfor %}

        {% endif %}
        {% block js %}

        {% endblock %}
    </div>
    
</body>
</html>

mkList/templates/navbar.html
<!-- Navbar    https://www.remove.bg/es/upload 
                https://www.youtube.com/watch?v=eTqHeeyA3bk
                https://www.youtube.com/watch?v=y7P6ytatRYk&list=PL_wRgp7nihyZsEnudJ-XUAEdnOGUojbnn
-->
{% load static %}
<nav class="navbar navbar-expand-lg py-3 mi_navbar">
  <div class="container mi_navbar">


    <a href="{% url 'client:gallery' %}" class="navbar-brand"><img src="{% static 'images/truebulb.webp' %}" alt="Todas" height="80" width=""></a>
    <h3 class="p-3 me_title">Show Code</h3>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu"
      style="color: rgb(194, 203, 17)">
      <span class="navbar-toggler-icon icon-bar"></span>
    </button>

    <div class="collapse navbar-collapse" id="navmenu">

      <ul class="navbar-nav ms-auto">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mi_ahref" href="#" id="navbarDropdownMenuLink" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">Vivero
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

            {% for categoria in menu_categorias %}
            <li>
              <a href="{% url 'appProduct:category' categoria.slug %}" class="dropdown-item mi_ahref">{{ categoria.categoria }}</a>
            </li>
            {% endfor %}

            <li><a href="{% url 'client:gallery' %}" class="dropdown-item mi_ahref">Todas</a></li>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link mi_ahref" href="{% url 'appClient:cliente' %}">Clientes</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mi_ahref" href="#" id="navbarDropdownMenuLink" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Productos
          </a>

          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a href="{% url 'appProduct:list_categoria' %}" class="dropdown-item mi_ahref">Categorias</a></li>
            <li><a href="{% url 'appProduct:list_colores' %}" class="dropdown-item mi_ahref">Colores</a></li>

            <li><a href="{% url 'appProduct:list_bulbo' %}" class="dropdown-item mi_ahref">Bulbos</a></li>
            <li><a href="#" class="dropdown-item">Listas</a></li>

          </ul>

          {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link mi_ahref" href="{% url 'appClient:mod_datos' request.user.id %}">Mis Datos </a>
        </li>
        <li class="nav-item">

          <span class="fs-6 fw-bold">
            <a class="nav-link mi_ahref" href="{% url 'client:logout' %}">SALIR - {{ user.username }} </a>
          </span>

        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>

        {% endif %}

        </li>
      </ul>
    </div>



  </div>
</nav>